---
title: "data_cleaning"
output: html_document
---

```{r}
library(tidyverse)
```

```{r read-data}
beauty_df <- read.csv("data/musical_instruments_cleaned.csv", stringsAsFactors = FALSE)
beauty_df <- beauty_df[beauty_df$title != "", ]


beauty_df_summary<- beauty_df %>% 
  group_by(asin) %>% 
  summarise(mean_rate = mean(overall, na.rm = TRUE), 
            mean_price = mean(price, na.rm = TRUE))#,
            # cnt = beauty_df %>% add_count(reviewerID) %>% select(n)) #%>% 
  # add_count(reviewerID)

```

```{r clean-data}
# Is there a correlation between product ratings on Amazon and various product-related features such as
# price, number of comments, and the superlatives used in comments

# weighted SE
model1 <- lm(overall ~ price, data=beauty_df)
summary(model1)
```

```{r text-cleaning}
library(tidytext)

beauty_review_words <- beauty_df %>%
  unnest_tokens(word, reviewText) %>%
  filter(str_detect(word, "[a-z']$"),
         !word %in% stop_words$word)

beauty_review_words2 <- beauty_review_words %>%
  count(asin, word, sort = TRUE) %>%
  ungroup()
```

```{r add text-features}
library(stringr)
# load("data/music_instruments_sentiments.RData")
beauty_df <- beauty_df %>% 
  mutate(num_char = nchar(reviewText),
         num_words = sapply(strsplit(reviewText, " "), length),
         num_allcaps = str_count(reviewText, "\\b[A-Z]{2,}\\b"),
         num_exemark = str_count(reviewText, "!"),
         num_qmark = str_count(reviewText, "\\?"),
         num_allmark = num_exemark + num_qmark
         )
```

```{r get-sentiment}
beauty_sentiments <- beauty_review_words %>%
  inner_join(get_sentiments("afinn"), by = "word") %>% # only leaving rows with words that are classified within afinn
  group_by(asin) %>%
  summarize(score = sum(score * n) / sum(n))

beauty_sentiments %>%
  mutate(asin = reorder(asin, score)) %>%
  ggplot(aes(asin, score, fill = score > 0)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  ylab("Average sentiment score")
```

```{r}
contributions <- beauty_review_words %>%
  inner_join(get_sentiments("afinn"), by = "word") %>%
  group_by(word) %>%
  summarize(occurences = n(),
            contribution = sum(score))

contributions
```

```{r}
contributions %>%
  top_n(25, abs(contribution)) %>%
  mutate(word = reorder(word, contribution)) %>%
  ggplot(aes(word, contribution, fill = contribution > 0)) +
  geom_col(show.legend = FALSE) +
  coord_flip()
```

```{r}
ggplot(beauty_df, aes(x=overall, y = price)) +
  geom_point()
```

```{r}
# aggregarted by each individual product
beauty_df_summary_senti <- beauty_df_summary %>% 
  left_join(beauty_sentiments)

model2 <- lm(mean_rate ~ mean_price*score, data = beauty_df_summary_senti)
summary(model2)
```

```{r}
plot(model2)
```

